# -*- coding: utf-8 -*-
"""fine-tuning final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MZyWhZzsHNUplwIMuVNPt61pAsQaMxTt
"""

!pip install -q transformers

import re
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, precision_recall_fscore_support, accuracy_score, confusion_matrix
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer, set_seed

from google.colab import files
files.upload();

tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
covid_words = ["covid", "coronavirus", "sars-cov-2", "corona virus", "pandemic"]

def clean(t):
    t = re.sub(r"http\S+|www\.\S+", " ", str(t))
    t = re.sub(r"<[^>]+>", " ", t)
    return re.sub(r"\s+", " ", t).strip()

def load(path):
    df = pd.read_csv(path)
    df["text"] = df["text"].apply(clean)
    df = df[df["text"].str.len() > 0].drop_duplicates("text").reset_index(drop=True)
    df["label"] = df["label"].astype(int)
    return df

def has_covid(t):
    t = t.lower()
    return any(w in t for w in covid_words)

english = load("english_training_final.csv")
mongolian = load("mongolian_expanded_FINAL.csv")
print("English:", len(english), " Mongolian:", len(mongolian))

class Claims(torch.utils.data.Dataset):
    def __init__(self, texts, labels):
        self.enc = tokenizer(list(texts), truncation=True, padding="max_length", max_length=128)
        self.labels = list(labels)
    def __len__(self):
        return len(self.labels)
    def __getitem__(self, i):
        item = {k: torch.tensor(v[i]) for k, v in self.enc.items()}
        item["labels"] = torch.tensor(int(self.labels[i]))
        return item

def train(train_df, seed, start_from="xlm-roberta-base"):
    set_seed(seed)
    model = AutoModelForSequenceClassification.from_pretrained(start_from, num_labels=2)
    args = TrainingArguments(output_dir="tmp", num_train_epochs=4,
                             per_device_train_batch_size=16, per_device_eval_batch_size=32,
                             learning_rate=2e-5, logging_steps=50, save_strategy="no",
                             seed=seed, report_to=[])
    trainer = Trainer(model=model, args=args, train_dataset=Claims(train_df["text"], train_df["label"]))
    trainer.train()
    return model

def score(model, test_df):
    model.eval()
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model.to(device)
    ds = Claims(test_df["text"], test_df["label"])
    loader = torch.utils.data.DataLoader(ds, batch_size=32)
    preds, gold = [], []
    with torch.no_grad():
        for batch in loader:
            y = batch.pop("labels")
            batch = {k: v.to(device) for k, v in batch.items()}
            preds += model(**batch).logits.argmax(-1).cpu().tolist()
            gold += y.tolist()
    macro = f1_score(gold, preds, average="macro")
    p, r, f, _ = precision_recall_fscore_support(gold, preds, labels=[0, 1], zero_division=0)
    print("  macro-F1: %.4f | accuracy: %.4f" % (macro, accuracy_score(gold, preds)))
    print("  misinfo recall: %.4f | reliable recall: %.4f" % (r[1], r[0]))
    print("  confusion:", confusion_matrix(gold, preds, labels=[0, 1]).tolist())
    return macro

en_train, en_test = train_test_split(english, test_size=0.20, stratify=english["label"], random_state=42)
mn_pool, mn_test = train_test_split(mongolian, train_size=100, stratify=mongolian["label"], random_state=42)
print("EN train/test:", len(en_train), len(en_test), " MN pool/test:", len(mn_pool), len(mn_test))

en_model = train(en_train, 42)

print("\nEnglish ceiling:")
ceiling = score(en_model, en_test)

print("\nRQ1 zero-shot Mongolian:")
zero_shot = score(en_model, mn_test)

en_model.save_pretrained("en_model")

import gc

seeds = [42, 123, 2024]
sizes = [0, 20, 40, 80, 100]
sweep = {}

for n in sizes:
    runs = []
    for seed in seeds:
        if n == 0:
            print("\nsize 0, seed %d (zero-shot):" % seed)
            runs.append(score(en_model, mn_test))
        else:
            if n >= len(mn_pool):
              sub = mn_pool.copy()
            else:
              sub, _ = train_test_split(mn_pool, train_size=n, stratify=mn_pool["label"], random_state=seed)
            m = train(sub, seed, start_from="en_model")
            print("\nsize %d, seed %d:" % (n, seed))
            runs.append(score(m, mn_test))
            del m; gc.collect(); torch.cuda.empty_cache()
    sweep[n] = (np.mean(runs), np.std(runs))

print("\n=== SWEEP (mean over seeds) ===")
print("English ceiling: %.4f" % ceiling)
for n, (mean, std) in sweep.items():
    print("MN %3d -> %.4f ± %.4f" % (n, mean, std))

import gc

constraint = english[english["source"].str.lower() == "constraint"]
pubhealth = english[english["source"].str.lower() == "pubhealth"]
pub_covid = pubhealth[pubhealth["text"].apply(has_covid)]
pub_other = pubhealth[~pubhealth["text"].apply(has_covid)]

en_covid = pd.concat([constraint, pub_covid])[["text", "label"]]
en_other_test = pub_other.reset_index(drop=True)
mn_covid = mongolian[mongolian["is_covid"] == 1][["text", "label"]]
mn_other_test = mongolian[mongolian["is_covid"] == 0].reset_index(drop=True)

train_df = pd.concat([en_covid, mn_covid], ignore_index=True)
print("COVID train:", len(train_df), "| EN-other test:", len(en_other_test), "| MN-other test:", len(mn_other_test))

en_scores, mn_scores = [], []
for seed in [42, 123, 2024]:
    m = train(train_df, seed)
    print("\nseed %d — English non-COVID:" % seed)
    en_scores.append(score(m, en_other_test))
    print("seed %d — Mongolian non-COVID:" % seed)
    mn_scores.append(score(m, mn_other_test))
    del m; gc.collect(); torch.cuda.empty_cache()

print("\n=== RQ4 (mean over seeds) ===")
print("English non-COVID: %.4f ± %.4f" % (np.mean(en_scores), np.std(en_scores)))
print("Mongolian non-COVID: %.4f ± %.4f" % (np.mean(mn_scores), np.std(mn_scores)))

